export const trendSkins = {
  CLEAN_MINIMAL_PRO: {
    label: 'Clean Minimal Pro',
    palette: {
      background: '#f5f7fb',
      accent: '#0f172a',
      accentAlt: '#4f46e5',
      text: '#0f172a',
      muted: '#475467',
    },
    texture: 'subtle-grain',
    overlay: 'corner-badge',
    iconStyle: 'outline',
    saturation: [0.8, 1.2],
    contrast: [1.0, 1.3],
    prompt: 'clean editorial minimal gradient, soft daylight, premium mockup',
  },
  COOL_BLUE_GLACIER: {
    label: 'Cool Blue Glacier',
    palette: {
      background: '#dceffd',
      accent: '#0e7490',
      accentAlt: '#164e63',
      text: '#0f172a',
      muted: '#0f4b66',
    },
    texture: 'frosted-glass',
    overlay: 'vertical-bar',
    iconStyle: 'solid',
    saturation: [0.9, 1.4],
    contrast: [1.1, 1.4],
    prompt: 'glacier mist, blue glass, cinematic shimmer',
  },
  GUMMY_GLOSS: {
    label: 'Gummy Gloss',
    palette: {
      background: '#ffe3f1',
      accent: '#ff5f8f',
      accentAlt: '#ff926b',
      text: '#18181b',
      muted: '#a855f7',
    },
    texture: 'glossy-bubbles',
    overlay: 'pill-badge',
    iconStyle: 'solid',
    saturation: [1.1, 1.6],
    contrast: [1.0, 1.2],
    prompt: 'candy coated studio lighting, gummy gloss reflections',
  },
  GLITCHY_GLAM: {
    label: 'Glitchy Glam',
    palette: {
      background: '#101128',
      accent: '#d946ef',
      accentAlt: '#22d3ee',
      text: '#f5f5f5',
      muted: '#a3a3f2',
    },
    texture: 'neon-noise',
    overlay: 'angled-bar',
    iconStyle: 'outline',
    saturation: [1.2, 1.5],
    contrast: [1.3, 1.6],
    prompt: 'neon glam, subtle glitch bloom, editorial lighting',
  },
  EDITORIAL_LUXE: {
    label: 'Editorial Luxe',
    palette: {
      background: '#f6ede3',
      accent: '#0f0f0f',
      accentAlt: '#c1844c',
      text: '#1c1917',
      muted: '#5f4b45',
    },
    texture: 'paper-grain',
    overlay: 'full-width-bar',
    iconStyle: 'outline',
    saturation: [0.9, 1.1],
    contrast: [1.0, 1.2],
    prompt: 'magazine editorial, luxe twilight, depth of field',
  },
  CREATOR_DESK: {
    label: 'Creator Desk',
    palette: {
      background: '#fbf6e9',
      accent: '#a16207',
      accentAlt: '#2563eb',
      text: '#1f2937',
      muted: '#6b7280',
    },
    texture: 'desk-grain',
    overlay: 'tab-badge',
    iconStyle: 'solid',
    saturation: [1.0, 1.3],
    contrast: [1.0, 1.25],
    prompt: 'creator studio, warm desk props, analog accents',
  },
};

export function resolveSkin(key = 'CLEAN_MINIMAL_PRO') {
  return trendSkins[key] || trendSkins.CLEAN_MINIMAL_PRO;
}
